name: Build masque-plus

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            arch: amd64
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup tools
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip tar jq
          YQ_VERSION=v4.44.3
          curl -sSL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
          chmod +x /usr/local/bin/yq
          if ! command -v gh >/dev/null 2>&1; then
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y gh
          fi
          chmod +x scripts/fetch_usque.sh

      - name: Read version
        id: v
        run: echo "ver=$(yq -r '.version' usque.yaml)" >> "$GITHUB_OUTPUT"

      - name: Fetch usque
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash scripts/fetch_usque.sh "${{ matrix.os }}" "${{ matrix.arch }}"

      - name: Build project artifacts
        run: |
          mkdir -p build/masque-plus/${{ matrix.os }}_${{ matrix.arch }}
          echo "${{ steps.v.outputs.ver }}" > build/masque-plus/${{ matrix.os }}_${{ matrix.arch }}/USQUE_VERSION.txt

      - name: Bundle usque binary into package
        run: |
          cp build/vendor/usque/${{ matrix.os }}_${{ matrix.arch }}/* build/masque-plus/${{ matrix.os }}_${{ matrix.arch }}/

      - name: Create zip per target
        run: |
          mkdir -p build/out
          cd build/masque-plus
          zip -r ../out/masque-plus-${{ matrix.os }}_${{ matrix.arch }}.zip ${{ matrix.os }}_${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: masque-plus-${{ matrix.os }}_${{ matrix.arch }}
          path: build/out/masque-plus-${{ matrix.os }}_${{ matrix.arch }}.zip
