name: Build masque-plus

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            arch: amd64
          - os: windows
            arch: arm64
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: linux
            arch: arm
            goarm: "7"
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Setup tools
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip tar
          YQ_VERSION=v4.44.3
          curl -sSL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
          chmod +x /usr/local/bin/yq
          if ! command -v gh >/dev/null 2>&1; then
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y gh
          fi
          chmod +x scripts/fetch_usque.sh

      - name: Fetch usque
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash scripts/fetch_usque.sh "${{ matrix.os }}" "${{ matrix.arch }}"

      - name: Build project
        env:
          CGO_ENABLED: 0
        run: |
          mkdir -p build/masque-plus/${{ matrix.os }}_${{ matrix.arch }}
          if [ "${{ matrix.os }}" = "windows" ]; then
            GOOS=windows GOARCH=${{ matrix.arch }} go build -o build/masque-plus/${{ matrix.os }}_${{ matrix.arch }}/masque-plus.exe .
          else
            if [ "${{ matrix.arch }}" = "arm" ] && [ -n "${{ matrix.goarm || '' }}" ]; then
              GOOS=${{ matrix.os }} GOARCH=arm GOARM=${{ matrix.goarm }} go build -o build/masque-plus/${{ matrix.os }}_${{ matrix.arch }}/masque-plus .
            else
              GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o build/masque-plus/${{ matrix.os }}_${{ matrix.arch }}/masque-plus .
            fi
          fi

      - name: Bundle usque binary into package
        run: |
          cp build/vendor/usque/${{ matrix.os }}_${{ matrix.arch }}/* build/masque-plus/${{ matrix.os }}_${{ matrix.arch }}/

      - name: Create flat zip per target
        run: |
          mkdir -p build/out
          cd build/masque-plus/${{ matrix.os }}_${{ matrix.arch }}
          zip -r ../../out/masque-plus-${{ matrix.os }}_${{ matrix.arch }}.zip .

      - name: Upload as artifact (CI only)
        uses: actions/upload-artifact@v4
        with:
          name: masque-plus-${{ matrix.os }}_${{ matrix.arch }}
          path: build/out/masque-plus-${{ matrix.os }}_${{ matrix.arch }}.zip

      - name: Upload to GitHub Release on tag
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          if ! gh release view "${TAG}" >/dev/null 2>&1; then
            gh release create "${TAG}" --title "${TAG}" --notes "Automated release for ${TAG}"
          fi
          gh release upload "${TAG}" "build/out/masque-plus-${{ matrix.os }}_${{ matrix.arch }}.zip" --clobber
